### ISSUE TITLE
document WSL/Windows issues

### ISSUE THREAD

**Issue by johrstrom** [ubccr/hpc-toolset-tutorial#104]
Looks like there's some setup for Windows folks, so getting some muscle memory and documentation around that would be nice.

Here are some things that come to my mind (but there could clearly be more):
1. Using WLS or Windows Desktop
2. You're likely going to need to update `docker-compose` (we probably need a minimum version listed somewhere)
3. When you install docker/docker-compose, you also likely need to:
   * create the `docker` group
   * add your user to it
   * start the docker daemon
   * ensure the docker socket is root:docker owner:group

**Comment by aebruno** [comment]
@johrstrom Just wanted to bump this as well. These came out of last years tutorial (thanks so much for taking notes!) so probably worth investigating to see what we can improve with the windows experience. CCing @dsajdak on this as well. It would seem like the WSL 2 backend is the way to go with docker on windows?

**Comment by dsajdak** [comment]
Minimum requirements are here: https://github.com/ubccr/hpc-toolset-tutorial/blob/master/docs/requirements.md and will be updated for this year.  Docker Desktop for Windows works great and includes latest version of docker-compose.  No need to install or update separately.  In the instructions we point to for installing Docker on the requirements page, there is a link for Windows installs using either Docker Desktop in Windows or if you have WSL2 enabled you'll be prompted to use Docker within that as well.  The instructions include info on adding your user (if non-admin) to the docker group.  The other things listed are done automatically with Docker Desktop in either environment so the easiest path is using that.
