### ISSUE TITLE
No SAML response provided

### ISSUE THREAD

**Issue by chansonZ** [ubccr/hpc-toolset-tutorial#106]
when longin XDMod : https://ip:4443 :

**No SAML response provided**
You accessed the Assertion Consumer Service interface, but did not provide a SAML Authentication Response. Please note that this endpoint is not intended to be accessed directly.

If you report this error, please also report this tracking number which makes it possible to locate your session in the logs available to the system administrator:

**Comment by aebruno** [comment]
@jpwhite4 and @ryanrath any thoughts on this?

**Comment by ryanrath** [comment]
@chansonZ @aebruno  So this looks like it could be caused by a misconfiguration of the SSO in XDMoD. @chansonZ have you made any changes to any of the `/etc/xdmod/simplesamlphp/metadata/*.php` files? What happens if you do a `./hpcts stop` and a `./hpcts start`?
