### ISSUE TITLE
localhost redirect ondemand

### ISSUE THREAD

**Issue by perrymil** [ubccr/hpc-toolset-tutorial#110]
Hi,

I am trying to setup the tutorial containers so that they serve the applications on the hostname of the server and not localhost. This is so that I and others at my site can remotely connect to the tutorial and test things out. It saves us time so that each of us don't have to install and configure the tutorial containers on our workstations. 

I was able to get coldfront, and xdmod to work by changing the ports item in the yaml file docker-compose.yml from localhost to the ip address of the server. 

It appears there is a redirect in the install.sh file for the ondemand container that shows:

`dex:
  client_redirect_uris:
    - "https://localhost:4443/simplesaml/module.php/authoidcoauth2/linkback.php"
    - "https://localhost:2443/oidc/callback/"
`

Which is I think the issue? I tried changing that to the hostname of the server, ran cleanup and then tried to start via hpcts start, but its still redirecting to localhost:3443 instead of using the servername:3443, ran cleanup, and then hpcts start again, but its still redirecting to localhost.

Do I need to change the hpcts script to --build instead of --no-build to get the containers to pull in those local changes?

Thanks!

**Comment by aebruno** [comment]
@perrymil Did you end up sorting this out? The HPC toolset containers are designed to be run locally for testing/development purposes but I do understand/appreciate your use case. 

> I tried changing that to the hostname of the server, ran cleanup and then tried to start via hpcts start, but its still redirecting to localhost:3443 instead of using the servername:3443, ran cleanup, and then hpcts start again, but its still redirecting to localhost.

Any changes you make to those files will require you to rebuild the OnDemand container image. For example, something along the lines of:

```
# Fined the image id for ondemand 
$ docker image list

# Remove the ondemand image
# docker rmi SOMEID

# Rebuild ondemand
$ docker-compose build ondemand
```

Hope this helps.
