### ISSUE TITLE
XDMoD PEARC22 issues

### ISSUE THREAD

**Issue by aebruno** [ubccr/hpc-toolset-tutorial#115]
Just creating an issue to keep track of getting the XDMoD containers ready for PEARC22 tutorial. Here's a start to the outstanding issues:

- [x] #113 
- [x] #114 
- [x] #112 
- [x] #124

**Comment by aebruno** [comment]
CC @ryanrath

**Comment by ryanrath** [comment]
Just an update, we're just waiting on some new releases for xdmod, xdmod-supremm, and supremm which I'm hoping to work on tomorrow with Jeff. As soon as those are out then I can finalize my changes and get a PR up.
