### ISSUE TITLE
cannot schedule jobs after stopping/starting containers

### ISSUE THREAD

**Issue by johrstrom** [ubccr/hpc-toolset-tutorial#119]
Previously we (open ondemand) were able to submit jobs without the account information (I checked the `ondemand/README.md` and you can see the GIF of this happening). That seems to have changed, at least for `hpcadmin`.

```
[hpcadmin@ondemand ~]$  sacctmgr -np list account format=account,partition,user
root|||
sfoster|||
staff|||
```

When I'm working through the tutorials, I've always just used `hpcadmin` without also going through the cold front tutorial (i.e., setting up account mappings and so on). 

Is there something I'm missing?

**Comment by dsajdak** [comment]
Are you unable to submit a job?  I was able to use 'salloc' to submit a job as the hpcadmin user.  I think the sacctmgr formatting is different with this version of slurm.

This works:
```
[hpcadmin@frontend ~]$ sacctmgr show account staff -s list format=cluster,account,partition,user
   Cluster    Account  Partition       User
---------- ---------- ---------- ----------
       hpc      staff
       hpc      staff              hpcadmin
```

or this:
```
[hpcadmin@frontend ~]$ sacctmgr show user hpcadmin -s list
      User   Def Acct     Admin    Cluster    Account  Partition     Share   Priority MaxJobs MaxNodes  MaxCPUs MaxSubmit     MaxWall  MaxCPUMins                  QOS   Def QOS
---------- ---------- --------- ---------- ---------- ---------- --------- ---------- ------- -------- -------- --------- ----------- ----------- -------------------- ---------
  hpcadmin      staff Administ+        hpc      staff                    1                                                                                      normal

```

I didn't try running a job in OnDemand though so maybe there is another issue?

**Comment by johrstrom** [comment]
The `staff` account seems to work. 

I pulled that `sacctmgr` command from a ticket we have to figure out what queues are available to you.  Which is to say, it was the wrong command (clearly) and I didn't know how to actually pull accounts (clearly).

Thanks!   Though, let's keep this ticket open so that we can document that you need to use the `staff` account or make a `~/.slurm/default`.

**Comment by johrstrom** [comment]
Seems like it's `AccountingStorageEnforce` in slurm.conf? That may have been the thing that switched?

In any case - I think just inlining a slurm default for the user is best (mostly because I don't want to redo those GIFs).

```
# ~/.slurm/defaults
account: staff
```

**Comment by johrstrom** [comment]
OK disregard - it is apparently working now?  I _may_ have just gotten a random error and attributed it to this because I know OSC changed this default and I guess assumed that was it?

Again, I can not replicate the issue so sorry for the noise!

**Comment by johrstrom** [comment]
I have to reopen this because now I can replicate.

**Comment by johrstrom** [comment]
I can't seem to get it to respond to `~/.slurm/defaults`.  @treydock  any ideas on what the path of least resistance is here?

```
[2022-07-01T15:26:48.264] _job_create: invalid account or partition for user 1001, account '(null)', and partition 'compute'
[2022-07-01T15:26:48.264] _slurm_rpc_submit_batch_job: Invalid account or account/partition combination specified
```

**Comment by aebruno** [comment]
@johrstrom The hpcadmin user should have Admin privs in slurm and the default account should be set. Have you tried starting fresh? i.e. cleaning up the old volumes `./hpcts cleanup` and starting from a fresh build?

**Comment by treydock** [comment]
So the account (group) must exist in Slurm database if using database.  If you are using database and want that defaults file to work you need this in slurm.conf:

```
CliFilterPlugins=user_defaults
```

**Comment by johrstrom** [comment]
OK - I think I got it. If you stop the containers, they stop to pickup the default value. This will definitely come up in the tutorials.

* clean up what you have
* start the containers, and see it start working
* issue `docker-compose down`
* issue `docker-compose up`
* now it won't work anymore.

**Comment by aebruno** [comment]
> OK - I think I got it. If you stop the containers, they stop to pickup the default value. This will definitely come up in the tutorials.
> 
>     * clean up what you have
> 
>     * start the containers, and see it start working
> 
>     * issue `docker-compose down`
> 
>     * issue `docker-compose up`
> 
>     * now it won't work anymore.

Thanks for tracking this down. I'll try and reproduce as well. Sounds like we have a bug somewhere with the container state.

**Comment by aebruno** [comment]
@johrstrom Thanks again for tracking this one down. I was able to re-produce. Looks like the culprit is the `StateSaveLocation=/var/lib/slurmd` directory not persisting between restarts. We currently do not mount this specific directory as a volume so it's destroyed after running `docker-compose down`. After mounting as a volume, this issue went away. Submitting a PR now that should fix this up.
