### ISSUE TITLE
OOD Desktops don't work

### ISSUE THREAD

**Issue by johrstrom** [ubccr/hpc-toolset-tutorial#121]
Desktops don't work because they fall victim to https://github.com/OSC/ood_core/issues/737 which I figure we should just drop-in patch in the image?

**Comment by aebruno** [comment]
@johrstrom Sounds good. Do we need to patch bc_desktop to not use the nohttpd flag? or do we need to patch TurboVNC? I wasn't quite clear on which app needs patching.

**Comment by aebruno** [comment]
> I think we can downgrade turbovnc or patch one of our libraries (basically just drop a new file in the container and/or `sed -i`).

Sounds good. Let's patch one our libraries as there are no arm64 builds for TurboVNC versions 2.2.x so we can't downgrade. They only provide arm64 builds for TurboVNC >3.0. Which files need the `sed -i` patch?
