### ISSUE TITLE
xdmod container doesnt start

### ISSUE THREAD

**Issue by pankajd-57** [ubccr/hpc-toolset-tutorial#140]
---> Open XDMoD Aggregate: Job Performance
xdmod | ERROR: unable to find configuration file "supremm_resources.json" in the
xdmod | XDMoD configuration directory "/etc/xdmod".
xdmod | This file should be created using the instructions in the install guide.
xdmod | 2022-07-07 12:42:10 [error] Caught exception while executing:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'modw_supremm.job'
doesn't exist (stacktrace: #0 /usr/share/xdmod/classes/CCR/DB/PDODB.php(158):
PDOStatement->execute(Array)
xdmod | #1 /usr/share/xdmod/classes/DB/EtlJournalHelper.php(34):
CCR\DB\PDODB->query('SELECT UNIX_TIM...')
xdmod | #2 /usr/lib64/xdmod/aggregate_supremm.php(105):
DB\EtlJournalHelper->getLastModified()
xdmod | #3 /usr/lib64/xdmod/aggregate_supremm.php(146): run_aggregation(Array,
Array)
xdmod | #4 {main})
xdmod | 2022-07-07 12:42:10 [critical] Filter list building failed:
SQLSTATE[42S02]: Base table or view not found: 1146 Table
'modw_aggregates.supremmfact_by_year' doesn't exist (stacktrace: #0
/usr/share/xdmod/classes/CCR/DB/PDODB.php(158): PDOStatement->execute(Array)
xdmod | #1
/usr/share/xdmod/classes/DataWarehouse/Query/TimeAggregationUnit.php(84):
CCR\DB\PDODB->query('SELECT
xdmod | ...', Array)
xdmod | #2 /usr/share/xdmod/classes/DataWarehouse/Query/Query.php(1378):
DataWarehouse\Query\TimeAggregationUnit->getDateRangeIds('0000-01-01',
'9999-12-31')
xdmod | #3 /usr/share/xdmod/classes/DataWarehouse/Query/Query.php(165):
DataWarehouse\Query\Query->setDuration(NULL, NULL)
xdmod | #4 /usr/share/xdmod/classes/DB/FilterListBuilder.php(74):
DataWarehouse\Query\Query->__construct('SUPREMM', 'year', NULL, NULL, 'none')
xdmod | #5 /usr/bin/xdmod-build-filter-lists(91):
FilterListBuilder->buildRealmLists('SUPREMM')
xdmod | #6 /usr/bin/xdmod-build-filter-lists(82): build(Array,
Object(CCR\Logger))
xdmod | #7 {main})
xdmod exited with code 1

**Comment by aebruno** [comment]
We're still in the process of polishing things up for PEARC22. In the mean time, some things to try.

1. Ensure you have pulled all the latest changes. This is very important as lots has changed:
 
```
$ git pull
```

2. Remove any old containers, volumes, and images:

```
$ ./hpcts cleanup
```

3. Pull down and start the most recent images:

```
$ ./hpcts start
```

**Comment by pankajd-57** [comment]
Thanks you..it worked.. How can I extend this to mu prodcution system..I mean how can I get these containers work for my systsem? Where I have to do changes so that it works for my system?

**Comment by aebruno** [comment]
> Thanks you..it worked.. How can I extend this to mu prodcution system..I mean how can I get these containers work for my systsem? Where I have to do changes so that it works for my system?

This project is for educational purposes only and should not be run in production.

**Comment by pankajd-57** [comment]
I mean, for our hpc facility.. Its for academic purpose
