### ISSUE TITLE
./hpcts start fails to run. Ubuntu focal. 

### ISSUE THREAD

**Issue by iamid0** [ubccr/hpc-toolset-tutorial#149]
Nice tutorial. 
But sorry to report an issue. 

OS Ubuntu Focal with the default kernel. 
Docker, Version:          20.10.18
Docker Compose version v2.10.2

```
git clone https://github.com/ubccr/hpc-toolset-tutorial.git
cd hpc-toolset-tutorial
./hpcts start
```
reports the following error msg, 

> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Edit docker-compose.yml, change `version: "3.9"`to `version: "2.2"`, then run ./hpcts start again, reports, 

>  Fetching latest HPC Toolset Images..
Pulling mongodb ... done
Pulling mysql   ... done
Starting HPC Toolset Cluster..
ERROR: Service 'base' needs to be built, but --no-build was passed.

Anyway, I have changed ${HPCTS_VERSION} to 2022.07, otherwise, there will be these error messages, 

> ERROR: no such image: ubccr/hpcts:ldap-"2022.07": invalid reference format. 

If I have made something wrong, please let me know. 
I am not quite familiar with docker.

**Comment by dsajdak** [comment]
@iamid0 I very much apologize for the delay in responding.  For some reason I never saw you issue.  We have recently updated the containers for our next presentation.  I recommend you do the following:

```
./hpcts destroy
git pull
./hpcts start
```

If this doesn't work you can try starting fresh with:

```
./hpcts cleanup
./hpcts start
```
