### ISSUE TITLE
Error message seen when logging in to ondemand

### ISSUE THREAD

**Issue by jpwhite4** [ubccr/hpc-toolset-tutorial#166]
The following message is printed when you ssh to the ondemand instance:
```bash
-bash: scl_source: No such file or directory
```

Steps to reproduce:
- from the outside ssh to frontend as hpcadmin `ssh -p 6222 hpcadmin@localhost`
- from frontent ssh to ondemand with this command `ssh ondemand`
- error message is printed after the MOTD

**Comment by johrstrom** [comment]
It appears to be this `~/.bash_profile`. I can't tell when these were changed from rhel/7 to 8, but since we're on 8, this `scl_source` isn't required for 8.

https://github.com/ubccr/hpc-toolset-tutorial/blob/85c3a8b4b58603a135c84a56516ff8cd9578d107/ondemand/install.sh#L93

**Comment by aebruno** [comment]
>  The following message is printed when you ssh to the ondemand instance:

I'm unable to reproduce. What OS/Docker version are you running? Can you double check you have the latest images: `./hpcts cleanup; ./hpcts start`.

> It appears to be this `~/.bash_profile`. I can't tell when these were changed from rhel/7 to 8, but since we're on 8, this `scl_source` isn't required for 8.

Sounds good. We should be able to just remove that line. However, while this line exists in the ondemand docker image it shouldn't be used anyway. We mount `/home` as [a volume](https://github.com/ubccr/hpc-toolset-tutorial/blob/master/docker-compose.yml#L196) and the home from the underlying image is not used.

This is what I see after running `./hpcts start`:

```
$ docker volume ls | grep home
local     hpc-toolset-tutorial_home

$ ssh -p 6222 hpcadmin@localhost
[hpcadmin@frontend ~]$ ssh ondemand
[hpcadmin@ondemand ~]$ cat /home/hpcadmin/.bash_profile 
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
```

**Comment by johrstrom** [comment]
Login to ondemand and it appears we add it again!

https://github.com/ubccr/hpc-toolset-tutorial/blob/85c3a8b4b58603a135c84a56516ff8cd9578d107/ondemand/initializers/dashboard.rb#L18-L21

**Comment by aebruno** [comment]
> Login to ondemand and it appears we add it again!

Ok then! Unless I'm missing something, it's a harmless warning correct? If so, we can add this to the TODO for PEARC23.

**Comment by johrstrom** [comment]
> Ok then! Unless I'm missing something, it's a harmless warning correct? If so, we can add this to the TODO for PEARC23.

Yea I can submit a patch soon while it's on our minds, but we don't need to release more containers. It is harmless and will keep until PEARC23.
