### ISSUE TITLE
MySQL corruption

### ISSUE THREAD

**Issue by treydock** [ubccr/hpc-toolset-tutorial#21]
I've had a few instances where if I do `docker-compose stop` then I start everything the MySQL instance will refuse to start because it needs repair.  I wonder if we should not make the mysql volume persist through container restarts?  Not sure how else to avoid MySQL database corruption or getting flagged that repairs are needed unless some config options we can set to auto-repair.

**Comment by aebruno** [comment]
One option might be to handle this in our entrypoint scripts? So initialize mysql databases if first run, otherwise run auto-repair in case of corruption?

**Comment by aebruno** [comment]
Think we're going to recommend folks stop and remove all containers and volumes so hopefully will mitigate this issue. Closing for now.
