### ISSUE TITLE
Coldfront fails to start

### ISSUE THREAD

**Issue by treydock** [ubccr/hpc-toolset-tutorial#35]
Command to start was `docker-compose up -d --build`

From `docker-compose ps`:

```
coldfront                     /usr/local/bin/entrypoint. ...   Exit 1                                                             
```

Logs:

```
$ docker-compose logs coldfront
Attaching to coldfront
coldfront    | ---> Starting SSSD on coldfront ...
coldfront    | ---> Starting sshd on coldfront...
coldfront    | ---> Starting the MUNGE Authentication service (munged) on coldfront ...
coldfront    | ---> Starting nginx on coldfront...
coldfront    | ---> Starting coldfront in gunicorn...
coldfront    | (Thu Jul 16 15:30:56 2020) [sssd[be[default]]] [sysdb_get_real_name] (0x0040): Cannot find user [nginx@default] in cache
coldfront    | (Thu Jul 16 15:30:56 2020) [sssd[be[default]]] [sysdb_get_real_name] (0x0040): Cannot find user [nginx@default] in cache
coldfront    | [2020-07-16 15:30:57 +0000] [47] [INFO] Starting gunicorn 20.0.4
coldfront    | [2020-07-16 15:30:57 +0000] [47] [ERROR] Retrying in 1 second.
coldfront    | [2020-07-16 15:30:58 +0000] [47] [ERROR] Retrying in 1 second.
coldfront    | [2020-07-16 15:30:59 +0000] [47] [ERROR] Retrying in 1 second.
coldfront    | [2020-07-16 15:31:00 +0000] [47] [ERROR] Retrying in 1 second.
coldfront    | [2020-07-16 15:31:01 +0000] [47] [ERROR] Retrying in 1 second.
coldfront    | [2020-07-16 15:31:02 +0000] [47] [ERROR] Can't connect to /srv/www/coldfront/coldfront.sock
```

The SSSD error is expected, it didn't find nginx user in LDAP which happens. Only way to avoid that error is tell SSSD to never lookup nginx in LDAP, but that's likely not why the container failed since nginx is in /etc/passwd.

**Comment by aebruno** [comment]
Can you confirm it's not related to the uid volume issue seen in #25? Did you run a `./hpcts clean` first? I haven't seen this error but I always wipe all volumes and start clean.

**Comment by dsajdak** [comment]
Yes I had this problem yesterday too and found I had alot of leftover volumes.  I deleted them all and then this worked again.  Now ./hpcts clean always cleans up the volumes.

**Comment by plessbd** [comment]
@jpwhite4 was also having an issue with something like this as well

**Comment by ericfranz** [comment]
I wonder if this is related to an experience I've had before. Sometimes I end up in a state where something is not running - so OnDemand was but XDMoD was inaccessible. So I did ./hpcts stop and then ./hpcts start and then XDMoD is inaccessible and OnDemand claims to be in maintenance mode.

![screen 2020-07-17 at 10 12 23 AM](https://user-images.githubusercontent.com/512333/87795431-06f86800-c816-11ea-84b6-2c5192ede352.png)

**Comment by ericfranz** [comment]
I also notice when starting up I see 

```Starting mongodb ... done
Starting ldap    ... done
Starting mysql                       ... done
Starting hpc-toolset-tutorial_base_1 ... done
Starting slurmdbd                    ... done
Starting slurmctld                   ... done
Starting cpn02                       ... done
Starting cpn01                       ... done
Starting frontend                    ... done
Starting xdmod                       ... done
Starting ondemand                    ... done
Starting coldfront                   ... done
```

But when stopping I see

```
Stopping ondemand  ... done
Stopping coldfront ... done
Stopping cpn02     ... done
Stopping cpn01     ... done
Stopping frontend  ... done
Stopping slurmctld ... done
Stopping slurmdbd  ... done
Stopping ldap      ... done
Stopping mongodb   ... done
Stopping mysql     ... done
```

Notice no xdmod. Will try ./hpcts clean first though

**Comment by treydock** [comment]
The issue with OnDemand maintenance is either something thinking /etc/ood/maintenance.enable is present or something wrong with rewrite conditions. It can be avoided by updating ood_portal.yml to disable maintenance rewrite rules:

```
use_maintenance: false
```

**Comment by ericfranz** [comment]
I am going to assume for now my issues are related to starting and stopping the containers after changing and/or doing a git pull to update my copy of this repo. Doing ./hpcts clean fixed the problem.

**Comment by aebruno** [comment]
> I am going to assume for now my issues are related to starting and stopping the containers after changing and/or doing a git pull to update my copy of this repo. Doing ./hpcts clean fixed the problem.

Great. It would be nice to get to the bottom of this as it seems like a bigger issue. Perhaps related to volume overlays in the containers? Next time you see this behavior can you double check the file permissions look sane:

```
ls -alh /home/
total 32K
drwxr-xr-x 8 root     root     4.0K Jul 17 13:31 .
drwxr-xr-x 1 root     root     4.0K Jul 17 13:31 ..
drwx------ 3 astewart astewart 4.0K Jul 17 13:31 astewart
drwx------ 3 cgray    cgray    4.0K Jul 17 13:31 cgray
drwx------ 3 csimmons csimmons 4.0K Jul 17 13:31 csimmons
drwx------ 3 hpcadmin hpcadmin 4.0K Jul 17 13:31 hpcadmin
drwxr-xr-x 3 pcp      pcp      4.0K Jul 17 13:31 pcp
drwx------ 3 sfoster  sfoster  4.0K Jul 17 13:31 sfoster
```

Coldfront needs the unix sock to have correct perms:

```
[hpcadmin@coldfront ~]$ ls -alh /srv/www/coldfront/coldfront.sock
srwxrwx--- 1 coldfront nginx 0 Jul 17 13:31 /srv/www/coldfront/coldfront.sock
```

If these are all wonky that would seem to indicate an issue with the volume? `/home` is mounted across most containers. It could be that for the tutorial we recommend always doing a `./hpcts clean` to ensure the volumes are removed and re-created?
