### ISSUE TITLE
coldfront check icons bad for colorblind users

### ISSUE THREAD

**Issue by michaelkarlcoleman** [ubccr/hpc-toolset-tutorial#81]
Not finding an obvious place for ColdFront bugs, but the icons are pretty bad for colorblind users like me.  The check and cross in addition to color help, but they're small enough that they're also kind of hard to distinguish (both being two lines crossing right angles).

Arguably it would be a lot better to just have text saying "YES" and "NO", for example.

![image](https://user-images.githubusercontent.com/5120/90575183-b86d1f00-e16f-11ea-86b3-2a5981ff27bf.png)

**Comment by dsajdak** [comment]
@michaelkarlcoleman thank you very much for this feedback.  I admit this is not something we considered and I apologize for that oversight.  We appreciate you bringing it to our attention!  I've created an issue in the ColdFront repo and we'll work on improving this as soon as we can.  https://github.com/ubccr/coldfront/issues/233

**Comment by michaelkarlcoleman** [comment]
@dsajdak No apology necessary, of course, but thank you for listening!

**Comment by aebruno** [comment]
@michaelkarlcoleman thanks for your feedback. Closing this out as it has been moved over to Coldfront.
